### Numpy - Numerical Python

In [1]:
# The convention is to import it as np
import numpy as np

In [2]:
np.__version__

'1.17.0'

Numpy arrays are similar to lists, except they only store one data type.
This makes them faster.

In [3]:
# We can create a numpy array from a list
my_array = np.array([1,2,3,4,5])
my_array

array([1, 2, 3, 4, 5])

In [4]:
type(my_array)

numpy.ndarray

In [5]:
# If we have a float in a numpy array, the entire array becomes floats
my_array_2 = np.array([1.1,2,3,4,5])
my_array_2

array([1.1, 2. , 3. , 4. , 5. ])

In [6]:
my_array.dtype

dtype('int32')

In [7]:
my_array_2.dtype

dtype('float64')

In [8]:
my_array_3 = np.array([1,2,3,4,5],dtype='float64')
my_array_3

array([1., 2., 3., 4., 5.])

In [9]:
my_array_3.dtype

dtype('float64')

In [10]:
# There are many different ways of creating an array. 
# Here are some common ones
np.arange(0,10) # (start,stop,step)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.linspace(0,1,11) # 11 values evenly spaced between 0 and 1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [12]:
np.ones((3,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [15]:
np.zeros((2,3,4),dtype=np.int64)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int64)

In [20]:
# We can create an array of random integers
np.random.randint(0,50,(2,4,5))

array([[[31, 22, 46, 27, 24],
        [ 3, 19, 32, 28, 41],
        [31, 26,  9,  2, 13],
        [ 3, 11, 16, 21, 48]],

       [[ 3, 11,  3, 13, 39],
        [29,  4, 17,  0, 17],
        [40, 42, 26,  5, 30],
        [14, 15,  8,  1, 37]]])

### Array Arithmetic

In [21]:
my_arr = np.array([[1,2,3,4],[5,6,7,8]])
my_arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
my_arr.shape

(2, 4)

In [23]:
my_arr + my_arr

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [24]:
my_arr * 5

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40]])

In [25]:
my_arr ** 0.5

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712]])

In [26]:
my_arr < 3

array([[ True,  True, False, False],
       [False, False, False, False]])

### Array indexing

In [27]:
my_arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [28]:
my_arr[1]

array([5, 6, 7, 8])

In [29]:
my_arr[1][2]

7

In [30]:
my_arr[1,2]

7

In [31]:
arr2 = np.arange(10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
my_slice = arr2[3:7]
my_slice

array([3, 4, 5, 6])

In [35]:
my_slice[2] = 88

In [36]:
arr2

array([ 0,  1,  2,  3,  4, 88,  6,  7,  8,  9])

In [37]:
# Indexing is [start:stop:step]
arr2[:4]

array([0, 1, 2, 3])

In [38]:
arr2[4:]

array([ 4, 88,  6,  7,  8,  9])

In [39]:
arr2[3:8]

array([ 3,  4, 88,  6,  7])

In [40]:
arr2[::2]

array([0, 2, 4, 6, 8])

In [41]:
arr3 = np.random.randint(0,50,(5,5))
arr3

array([[33, 40, 43, 21, 28],
       [ 4, 26, 11, 35, 39],
       [33, 30,  8,  0,  1],
       [18, 35, 15, 20, 42],
       [47, 14, 32,  3, 32]])

In [42]:
arr3[:4,1:4]

array([[40, 43, 21],
       [26, 11, 35],
       [30,  8,  0],
       [35, 15, 20]])

In [43]:
arr3[:,::2]

array([[33, 43, 28],
       [ 4, 11, 39],
       [33,  8,  1],
       [18, 15, 42],
       [47, 32, 32]])

In [44]:
arr3[:,0]    # First column

array([33,  4, 33, 18, 47])

In [45]:
arr3[0,:]    # First row

array([33, 40, 43, 21, 28])

In [46]:
arr3 > 22

array([[ True,  True,  True, False,  True],
       [False,  True, False,  True,  True],
       [ True,  True, False, False, False],
       [False,  True, False, False,  True],
       [ True, False,  True, False,  True]])

In [47]:
# We can create a mask to select only those values that are true
arr3[arr3 > 22]

array([33, 40, 43, 28, 26, 35, 39, 33, 30, 35, 42, 47, 32, 32])

In [48]:
arr3.T

array([[33,  4, 33, 18, 47],
       [40, 26, 30, 35, 14],
       [43, 11,  8, 15, 32],
       [21, 35,  0, 20,  3],
       [28, 39,  1, 42, 32]])

In [49]:
arr4 = np.array([1,2,3])
arr5 = np.array([4,5,6])

In [50]:
np.concatenate([arr4,arr5])

array([1, 2, 3, 4, 5, 6])

In [51]:
arr6 = np.array([[7,8,9],[10,11,12]])

In [52]:
np.concatenate([arr6,arr6])

array([[ 7,  8,  9],
       [10, 11, 12],
       [ 7,  8,  9],
       [10, 11, 12]])

In [53]:
np.concatenate([arr6,arr6],axis=1)

array([[ 7,  8,  9,  7,  8,  9],
       [10, 11, 12, 10, 11, 12]])

In [54]:
np.vstack([arr4,arr6])

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [10, 11, 12]])

In [55]:
arr7 = np.array([[70],[80]])
np.hstack([arr6,arr7])

array([[ 7,  8,  9, 70],
       [10, 11, 12, 80]])

In [58]:
arr3.min(axis=0)

array([ 4, 14,  8,  0,  1])

In [59]:
arr3.min(axis=1)

array([21,  4,  0, 15,  3])

In [60]:
arr3.min()

0

In [61]:
arr3.mean()

24.4

In [62]:
arr3.mean(axis=0)

array([27. , 29. , 21.8, 15.8, 28.4])

In [63]:
arr3.mean(axis=1)

array([33. , 23. , 14.4, 26. , 25.6])

In [64]:
np.sqrt(arr3)

array([[5.74456265, 6.32455532, 6.55743852, 4.58257569, 5.29150262],
       [2.        , 5.09901951, 3.31662479, 5.91607978, 6.244998  ],
       [5.74456265, 5.47722558, 2.82842712, 0.        , 1.        ],
       [4.24264069, 5.91607978, 3.87298335, 4.47213595, 6.4807407 ],
       [6.8556546 , 3.74165739, 5.65685425, 1.73205081, 5.65685425]])